export const getCountryFlag = (countryName: string): string => {
  const flags: Record<string, string> = {
    England: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    Brazil: "🇧🇷",
    Argentina: "🇦🇷",
    France: "🇫🇷",
    Germany: "🇩🇪",
    Spain: "🇪🇸",
    Portugal: "🇵🇹",
    Netherlands: "🇳🇱",
    Morocco: "🇲🇦",
    USA: "🇺🇸",
    Japan: "🇯🇵",
    Croatia: "🇭🇷",
    Switzerland: "🇨🇭",
    Belgium: "🇧🇪",
    Senegal: "🇸🇳",
    Colombia: "🇨🇴",
    Mexico: "🇲🇽",
    Australia: "🇦🇺",
    Canada: "🇨🇦",
    Norway: "🇳🇴",
    Paraguay: "🇵🇾",
    Ecuador: "🇪🇨",
    Ghana: "🇬🇭",
    Algeria: "🇩🇿",
    Austria: "🇦🇹",
    "Cape Verde": "🇨🇻",
    "Congo DR": "🇨🇩",
    "Bosnia & Herzegovina": "🇧🇦",
    Egypt: "🇪🇬",
    Vietnam: "🇻🇳",
    Myanmar: "🇲🇲",
  };
  return flags[countryName] || "🏳️";
};